### PR TITLE
Refactor `client.today` and `client.yesterday`

### PR DESCRIPTION
**Pull request by noriapi**
Since most parts of `client.today` and `client.yesterday` are the same code, i extracted it as `client._daily`.

### CODE REVIEW

**Comment by noriapi** [comment]
Sorry, I don't know how the refactoring should be described in keep a changelog.

**Comment by epwalsh** [comment]
Thanks @noriapi, this is great. For the CHANGELOG, I would just add something like this:

```markdown
### Changed

- (internal) Refactored daily note creation
```

**Comment by noriapi** [comment]
> Thanks @noriapi, this is great. For the CHANGELOG, I would just add something like this:
> 
> ```
> ### Changed
> 
> - (internal) Refactored daily note creation
> ```

Thank you, I added it to CHANGELOG.

**Review by epwalsh — APPROVED** [review]
LGTM. Thanks @noriapi :)

**Pull request merged**
