### PR TITLE
Refactor workspaces

### PR DESCRIPTION
**Pull request by adam-devel**
this is a draft PR to decide how to go about this.
- clients must not attach to any specific root vault
  - clients must have a set of vaults (`client.workspaces`) and a currently used vault (`client.current_workspace`).
  - `client.dir` must be removed, use `.current_workspace`
  - `workspace.path` should be of type `plenary.path` if it's going to replace `client.dir`
  - `client:vault_root` should be removed
  - `obsidian.new_from_dir` should be removed
  - get rid of `templates_dir` as well ? this needs discussion
- auto command registration and clearing should happen through the workflow module, maybe `workflow:register(callback)` and `workflow:clear()`.
- we should simplify the `detect_cwd` logic: `Workspace.new_from_cwd`, `Workspace.get_workspace_from_cwd`, and `Workspace.get_default_workspace` only call each other and are not used by any other modules, the separation of the logic into these different functions unnecessary.
- we should figure out a way to deal with templates:
  from https://github.com/epwalsh/obsidian.nvim/issues/190#issuecomment-1837511113:
  > - should templates be read at some chosen "main vault" root directory (the way it's done right now)
  > - or should it be read relative to the current workspace ?
  > - or should it be a per-workspace option: `{name="foo", path="bar", template_configs..}` ?

### CODE REVIEW

**Comment by adam-devel** [comment]
it's really hard to stay within the scope of this pull request, this refactor touches almost all the other modules.
i am tempted to refactor the whole thing for my personal convenience, for example i don't use templates and i don't want to deal with them so i will just remove them.
i don't want to maintain my own fork however so i will try to contribute back as much as i can so that i don't need my own fork.

**Comment by adam-devel** [comment]
>>`client:vault_root` should be removed
>
>Why should we remove that?

depending on where you want workspace management to be, the client is either going manage a single vault or is going to manage multiple vaults.

for a single vault/workspace, `client:vault_root` becomes redundant with `client.current_workspace.path`.

for multiple vaults/workspaces, it's not clear which workspace's root `client:vault_root` resolve:
  - if it resolves the current workspace's root, `current_workspace` already exists.
  - if it resolves to some other workspace's root, every workspace already has a `path` field

> Alternatively that could replace client.dir.

assuming `client.dir` is the directory of the current workspace: replacing it with a function seems unnecessary as workspaces already has a `path`

to conclude: the function may seem useful somewhere outside the client module but let's remember that we require explicit paths to vaults/workspaces during `setup`, this existing expectation already makes implicit vault discovery unnecessary imo.

**Comment by epwalsh** [comment]
> for a single vault/workspace, client:vault_root becomes redundant with client.current_workspace.path.

I see. From my perspective `client:vault_root()` / `client.dir` are a convenience for accessing `client.current_workspace.path`. But I don't like how we have both `client:vault_root()` and `client.dir`. One of these should definitely be removed.

**Comment by adam-devel** [comment]
That's a valid perspective, sometimes it's useful to have shortcuts like that. I thought I had a deeper misunderstanding.

**Comment by epwalsh** [comment]
I'm hoping to find some time over the holiday break to continue to clean this stuff up 🤞

**Comment by epwalsh** [comment]
I think the workspace API is in a much better spot now, and the library has evolved substantially since this PR anyway, so I'm going to close.

**Pull request closed without merging**
