### PR TITLE
Added configuration option `disable_frontmatter` (outp1#42)

### PR DESCRIPTION
**Pull request by outp1**
This commit will solve this [issue](https://github.com/epwalsh/obsidian.nvim/issues/42).

### CODE REVIEW

**Review by epwalsh — APPROVED** [review]
LGTM, thanks @outp1!

**Comment by saccarosium** [comment]
Hi,
It seems that the option doesn't work, on my system.

my config:
```lua
require("obsidian").setup({
  dir = "~/Documents/nextcloud/notes/",
  note_frontmatter_func = nil,
  notes_subdir = "notes",
    completion = {
      nvim_cmp = true, -- if using nvim-cmp, otherwise set to false
    }
  })

  vim.keymap.set("n", "gf", function()
    if require('obsidian').util.cursor_on_markdown_link() then
      return "<cmd>ObsidianFollowLink<CR>"
    else
      return "gf"
   end
  end,
  { noremap = false, expr = true })

vim.keymap.set("n", "<leader>on", ":ObsidianNew<CR>")
vim.keymap.set("n", "<leader>os", ":ObsidianSearch<CR>")
```
Is located under `after/plugin` but I tested also on `plugin`. I don't know what the problem is.

**Comment by fermifunktion** [comment]
Hi,
on my system `disable_frontmatter = true` is also not working within the `require("obsidian").setup()` function:

``` lua
require("obsidian").setup({
  dir = "~/Obsidian",
  note_id_func = function(title)
    -- Create note IDs in a Zettelkasten format with a timestamp and a suffix.
    local suffix = ""
    if title ~= nil then
      -- If title is given, transform it into valid file name.
      suffix = title:gsub(" ", "-"):gsub("[^A-Za-z0-9-]", ""):lower()
    else
      -- If title is nil, just add 4 random uppercase letters to the suffix.
      for _ = 1, 4 do
        suffix = suffix .. string.char(math.random(65, 90))
      end
    end
    -- return tostring(os.time()) .. "-" .. suffix
    return title
   end,
    completion = {
    nvim_cmp = true, -- if using nvim-cmp, otherwise set to false
  },
  disable_frontmatter = true,
})
```
I am using `neovim v0.8.3` on `Arch Linux, Kernel 6.1.11`

**Comment by epwalsh** [comment]
Just pushed a fix.

**Comment by TLSingh1** [comment]
Hi, thank you for your work.

Unfortunately, this doesnt disable it for me. I tried with latest commit and the one specified above. Using packer.

```
		use({
			"epwalsh/obsidian.nvim",
                        commit = "3d45970",
			config = function()
				require("obsidian").setup({
					use_advanced_uri = true,
					dir = "~/brain",
					completion = {
						nvim_cmp = true,
					},
                                        disable_frontmatter = true,
				})
			end,
		})

```

**Pull request merged**
