### PR TITLE
Add short demo for new users

### PR DESCRIPTION
**Pull request by shakesbeare**
Adds demonstration video as requested in #41. 

I had a guess at the commands I thought would be most commonly used to show off in a demo that's just over 30s.

### CODE REVIEW

**Review by epwalsh — APPROVED** [review]
This is great! Thank you

**Comment by vimpostor** [comment]
Looks like you uploaded the demo video to a non-permanent address, because the video in the README is broken.
I also don't see the video in your fork's commit history anymore, which is why Github may have garbage collected the video.

**Comment by epwalsh** [comment]
Hm, it looks like something weird has happened. It doesn't render like it used to for me.

**Comment by epwalsh** [comment]
I think I may have fixed it.

**Pull request merged**
