### PR TITLE
Adding support for Mini.Pick plugin in the command `ObsidianSearch`

### PR DESCRIPTION
**Pull request by bassamsdata**
related to #256. it's working but only if started neovim in the same directory of the obsidian vault though.
I need help in correcting this.
thank you

### CODE REVIEW

**Comment by bassamsdata** [comment]
I'm not sure why, but changing the function style to double brackets `()` fixed it. I attempted to match the style of previous plugin functions, but that caused the problem.

The pull request is now functional.

**Review by epwalsh — COMMENTED** [review]
Thanks @bassamsdata and sorry for the slow response. Overall looks pretty good. We also need to add this into the `ObsidianQuickSwitch` and `ObsidianTemplate` commands (both in `lua/obsidian/command.lua`). 

> it's working but only if started neovim in the same directory of the obsidian vault though.

Is this a bug with mini.pick? Might be worth opening an issue there. I think it's okay for now if we can't fix it though. We could add a disclaimer.

**Comment by bassamsdata** [comment]
appreciate the review! i've included support for `obsidianquickswitch` and `obsidiantemplate`.

> Is this a bug with mini.pick? Might be worth opening an issue there. I think it's okay for now if we can't fix it though. We could add a disclaimer.

it resolved now, functioning smoothly like telescope wherever nvim is initiated. no need for a disclaimer. 

also, added `mini.pick`to the readme file.

**Comment by epwalsh** [comment]
@bassamsdata I accidentally screwed up this PR while trying to push a minor README update. Luckily I still have the commit history, just on a different branch now: https://github.com/epwalsh/obsidian.nvim/pull/270

**Pull request closed without merging**
