### PR TITLE
Add option to configure path to Obsidian.app on MacOS

### LINKED ISSUE #304: Configure ObsidianOpen to look into a specific folder
### 🚀 The feature, motivation and pitch

Currently using NIX to manage my system app and home-manager creates an app inside /Applications/ in mac os.
Configuring the ObsidianOpen to point to a path specified in the config would be optimal.

Example below:
스크린샷 2024-01-05 19 34 31

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by epwalsh**
Closes #304

### CODE REVIEW

**Comment by tommasobruno** [comment]
When I run the command from the neovim terminal it works fine, but when I run the ObsidianOpen it gives error:
스크린샷 2024-01-05 21 34 06
스크린샷 2024-01-05 21 34 26

**Comment by tommasobruno** [comment]
Looks like the problem is within the URI set up.
스크린샷 2024-01-05 21 44 01

**Comment by epwalsh** [comment]
@tommasobruno that might be a different error. Try quoting the URI.

**Comment by tommasobruno** [comment]
> @tommasobruno that might be a different error. Try quoting the URI.

Other error:
스크린샷 2024-01-05 21 58 05

**Comment by epwalsh** [comment]
Ok so `../bin/obsidian` seems like the wrong path.

**Comment by tommasobruno** [comment]
> Ok so `../bin/obsidian` seems like the wrong path.

It's weird, because if the don't include the URI at the end, the app opens normally

**Comment by epwalsh** [comment]
Very weird. 🤔

**Comment by eblume** [comment]
Apologies for the double-post but I want to be sure this doesn't get lost: https://github.com/epwalsh/obsidian.nvim/issues/304#issuecomment-2270031837

In summary: I believe this may have been closed in error. The .app bundle is located within the nix store, but whether you use that .app bundle or the package-provided `obsidian` wrapper, they both work with the command detailed above.

**Comment by ajmichels** [comment]
I agree that this was maybe closed prematurely. Is there another effort to resolve this in a different way? It isn't really clear why exactly this PR was closed. Seems like one person was running into an issue that might not be representative of others and the PR was closed. Please reconsider this change. Thank you.

Because of policy restrictions on my work machine I am forced to install Obsidian in `~/Applications/Obsidian.app` so I am also not able to use any of the commands that attempt to open in the Obsidian app. It seems like having the `obsidian_app` option would still be really useful.

The following command works just fine for me when I run it manually so having this option seems like it would resolve at least some issues for some people.

```
open -a ~/Applications/Obsidian.app --background 'obsidian://open?vault=Notes&file=file%20to%20open.md'
```

**Pull request closed without merging**
