### PR TITLE
feat: ObsidianQuickSwitch command

### PR DESCRIPTION
**Pull request by joserc87**
Hi!
As requested in #66, I'd like to quickly open an Obsidian note, so I created a new command for this. Since in the Obsidian App this action (`Ctrl-O`) is called "Open Quick Switcher", I called the command `:ObsidianQuickSwitch`, because `:ObsidianOpenQuickSwitcher` is longer than needed. Of course, I'm open for suggestions.

Thank you!

### CODE REVIEW

**Comment by joserc87** [comment]
Any feedback on the code is very much welcome, because I'm quite new to lua (specifically, I don't know if there exists a function already for converting a list of strings to a single string; if there is I'm happy to remove the function `table_params_to_str`).

**Review by epwalsh — COMMENTED** [review]
Thanks @joserc87, this looks great! Looks like there's just some minor lint/style issues that CI is complaining about. Once you fix those I'll hit the merge button!

**Comment by joserc87** [comment]
All the CI issues should be fixed now @epwalsh .

Since I started this PR a couple of weeks ago, other PRs got merged in, in particular to add support for `fzf-lua`, so I had to deal with some merge conflicts. The command that I added doesn't take fzf-lua into account, so it doesn't work with it, it requires either FZF or Telescope. At first I was thinking to add support for `fzf-lua`, but I think I should do something more clever than copying the code with the `if has_fzf_lua` etc, to keep the code maintainable...

I can add the support for fzf-lua  as part of a separate PR, so that we can merge this one and I don't get ever more merge conflicts... :) Do you agree?

**Review by epwalsh — APPROVED** [review]
> I can add the support for fzf-lua as part of a separate PR, so that we can merge this one and I don't get ever more merge conflicts... :) Do you agree?

Sounds good to me! FYI @saccarosium

**Pull request merged**
