### PR TITLE
feat: add daily_notes.folder option

### PR DESCRIPTION
**Pull request by metalelf0**
Hey, sorry for the delay, I've been quite busy recently.

Here I added the option to customize the dailies path. Let me know if you think this solution is ok, it should be much cleaner than the previous one. I copied your implementation for the `notes_subdir` option.

### CODE REVIEW

**Review by epwalsh — COMMENTED** [review]
Hey @metalelf0 this is a great start! Did you see my comment [here](https://github.com/epwalsh/obsidian.nvim/issues/15#issuecomment-1256406320)? What do you think about changing `dailies_path: ""` to `daily_notes: { folder: "", ... }`, i.e. mimic the JSON structure of `.obsidian/daily-notes.json`?

**Comment by metalelf0** [comment]
Hi, I read it but I was unsure whether to follow that approach or to keep the same naming convention of `notes_subdir`. If you think it's more important to mimic the Obsidian JSON configuration, I will change it!

**Comment by epwalsh** [comment]
>  If you think it's more important to mimic the Obsidian JSON configuration, I will change it!

I do think that would be nice because it presents a natural way to add support for more core Obsidian plugins in the future. We could also automatically load that part of the config from the corresponding `.obsidian/*.json` file.

**Review by epwalsh — APPROVED** [review]
This looks great! Thanks so much @metalelf0 :)

**Pull request merged**
